#ifndef CONFIG_H
#define CONFIG_H

#define NODUS_VERSION "0.2.0"
#define SERIAL_BAUD_RATE 115200
#define STATE_CHANGE_INTERVAL_MS 3000

// Display OLED SSD1306
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define SCREEN_ADDRESS 0x3C

// Animation
#define BLINK_MIN_INTERVAL_MS 3000
#define BLINK_MAX_INTERVAL_MS 7000
#define BLINK_DURATION_MS 150

#endif
